name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.10.7", "9.2.5"]
        cabal: ["3.8.1.0"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Haskell
      id: setup-haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        cabal-update: false

    - name: Cabal update
      run: cabal update

    - name: Record cabal dependencies
      id: record-deps
      run: |
        cabal build all --dry-run

    - name: Cache cabal store
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}-

    - name: Install cabal dependencies
      run: cabal build --only-dependencies --enable-tests --enable-benchmarks all

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: cabal test all

  stylish-haskell:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.2.5"]
        cabal: ["3.8.1.0"]
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install system dependencies (apt-get)
      run: |
        sudo apt-get update
        sudo apt-get -y install fd-find

    - name: Setup Haskell
      id: setup-haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        cabal-update: false

    - name: Cabal update
      run: cabal update

    - name: Setup cabal bin path
      run: echo "$HOME/.cabal/bin" >> $GITHUB_PATH

    - name: Cache cabal store
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal-stylish
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-stylish-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-stylish-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-stylish-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}-

    - name: Install stylish-haskell
      run: cabal install stylish-haskell --constraint 'stylish-haskell == 0.14.4.0'

    - name: Record stylish-haskell version
      run: |
        which stylish-haskell
        stylish-haskell --version

    - name: Run stylish-haskell
      run: |
        ./scripts/format-stylish.sh -p . -d
        git diff --exit-code